from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True)
class DataConfig:
    dataset_path: Path
    train_split: str
    validation_split: str
    test_split: str
    horizon: int
    delta_t_hours: float
    # Whether price is a known customer tariff derived from calendar context,
    # rather than a stochastic trajectory generated by the scenario model.
    deterministic_price: bool = False
    # Deterministic sensitivity applied around tariff_reference_price_per_mwh:
    # reference + scale * (published_tariff - reference).  It changes the
    # declared tariff case without altering the raw dataset.
    tariff_spread_scale: float = 1.0
    tariff_reference_price_per_mwh: float = 0.0
    # Original feeder bus supplying the co-located PV trace when reducing to a
    # single PCC. PCC demand itself is the calibrated data-center facility model.
    pcc_source_bus: str = "675"
    # Installed PV capacity behind the reduced PCC. The source-bus trajectory is
    # normalized by its original nameplate rating and rescaled to this value.
    pcc_pv_capacity_mw: float = 5.0


@dataclass(frozen=True)
class CVAEConfig:
    latent_dim: int
    hidden_dim: int
    epochs: int
    learning_rate: float
    beta: float
    ramp_weight: float
    batch_size: int = 64
    kl_warmup_epochs: int = 40
    active_load_weight: float = 0.20
    reactive_load_weight: float = 0.10
    pv_weight: float = 0.20
    workload_weight: float = 0.10
    pue_weight: float = 0.05
    price_weight: float = 0.25
    carbon_weight: float = 0.10
    net_load_weight: float = 0.15
    net_peak_weight: float = 0.20
    price_spread_weight: float = 0.20
    carbon_spread_weight: float = 0.20

    def field_weights(self) -> tuple[float, ...]:
        """Per-field reconstruction weights: P, Q, PV, workload, PUE, price, carbon.

        The CVAE reconstruction and feasibility fine-tuning share these values.
        """

        return (
            self.active_load_weight,
            self.reactive_load_weight,
            self.pv_weight,
            self.workload_weight,
            self.pue_weight,
            self.price_weight,
            self.carbon_weight,
        )


@dataclass(frozen=True)
class GeneratorConfig:
    kind: str = "cvae"


@dataclass(frozen=True)
class DFLConfig:
    num_support_scenarios: int
    epochs: int
    final_validation_size: int
    device: str
    method: str = "recourse_feasibility"
    # False starts a fresh generator inside train_dfl instead of loading the
    # separately pretrained checkpoint. Normalization is still loaded from the
    # fitted codec because it describes the data, not learned model weights.
    initialize_from_pretrained: bool = True
    training_relative_gap: float = 0.0
    training_allow_carbon_slack: bool = False
    # How fixed validation and reported test subsets approximate the held-out
    # distribution. ``farthest`` reproduces historical runs and assigns uniform
    # weights to deliberately extreme points. ``kmeans`` uses cluster medoids
    # with cluster-mass weights and is the statistically meaningful default for
    # dataset v2 configurations.
    evaluation_selection_rule: str = "farthest"
    # Checkpoint objective. "economic" minimizes exact validation regret;
    # "carbon_first" first enforces the shedding tolerance, then minimizes
    # carbon excess and finally uses regret as a tie-breaker.
    checkpoint_selection: str = "economic"
    checkpoint_shedding_tolerance: float = 1.0e-4
    # Reliable checkpoints within this absolute tCO2/MWh distance of the
    # lowest validation carbon-excess rate compete on economic regret. Zero
    # retains strict lexicographic carbon-first selection.
    checkpoint_carbon_tolerance: float = 0.0
    # Direct CVAE fine-tuning with recourse-aware feasibility feedback. With
    # scratch initialization, zero trains only the statistical CVAE objective
    # for the same epoch budget. After separate pretraining, zero is a no-op.
    lambda_dfl: float = 0.0
    feasibility_load_weight: float = 1.0
    feasibility_pv_weight: float = 1.0
    feasibility_carbon_weight: float = 1.0
    # Expensive planning/recourse solves are performed once every N epochs,
    # after the optional statistical-only warm-up.
    dfl_start_epoch: int = 0
    dfl_eval_interval: int = 1
    decision_batch_size: int = 4
    # Reuse the same stratified real-scenario anchors and latent draws at every
    # DFL epoch.  This removes Monte-Carlo target drift from the already noisy
    # detached-solver feedback while the reconstruction minibatch stays random.
    fixed_decision_anchors: bool = True
    use_solution_cache: bool = True
    # Paper-inspired Odece trade-off.  IPL discourages optimistic constraint
    # predictions whose design fails under truth; OPL discourages predictions
    # so conservative that the true optimal design is excluded.
    infeasibility_aversion_alpha: float = 0.5
    feasibility_margin: float = 0.05
    # Keep the reconstruction batch statistically meaningful while the much
    # more expensive MILP decision batch remains small.  Zero reuses
    # cvae.batch_size.
    reconstruction_batch_size: int = 0
    # Once decision feedback starts, retain a smaller statistical objective as
    # a distributional regularizer instead of letting it dominate the decoder.
    dfl_statistical_weight: float = 0.20
    validation_interval: int = 1
    # Dynamically rescale the DFL term so its decoder-gradient norm is this
    # fraction of the statistical gradient norm.  Zero disables balancing.
    gradient_balance_ratio: float = 0.20
    gradient_balance_min_scale: float = 1.0
    gradient_balance_max_scale: float = 1000.0


@dataclass(frozen=True)
class DataCenterConfig:
    """Facility power model at the data-center bus, in MW.

        power(t) = non_it_mw + PUE(t) * (it_base_mw + it_workload_mw * processed(t))

    ``workload_arrival`` and ``pue`` are dimensionless series in the dataset, so
    these three coefficients alone set the facility's scale.  Changing them
    rescales the data center without touching the dataset or any trained
    generator; only the planning results depend on them.

    The defaults give a roughly 10 MW-peak facility with a high, continuous
    base load. They are calibrated case-study parameters, not metered facility
    data.
    """

    non_it_mw: float = 0.75
    it_base_mw: float = 5.0
    it_workload_mw: float = 3.75
    # Maximum number of intervals by which unfinished arrivals may be deferred.
    # Zero fixes processed work to the arrival trace and is useful for measuring
    # how much workload shifting substitutes for storage.
    workload_max_delay_hours: int = 2
    workload_processing_upper: float = 1.20

    def power_mw(self, pue: float, processed: float) -> float:
        return self.non_it_mw + pue * (self.it_base_mw + self.it_workload_mw * processed)


@dataclass(frozen=True)
class PlanningConfig:
    max_storage_sites: int
    initial_soc: float
    initial_carbon_intensity: float
    min_soc: float
    max_soc: float
    charge_efficiency: float
    discharge_efficiency: float
    self_discharge: float
    min_power_mw: float
    max_power_mw: float
    min_energy_mwh: float
    max_energy_mwh: float
    min_duration_hours: float
    max_duration_hours: float
    grid_limit_mw: float
    carbon_intensity_max: float
    dc_carbon_cap: float
    other_bus_carbon_cap: float
    carbon_formulation: str
    flow_limit_formulation: str
    solver_time_limit_seconds: float
    solver_relative_gap: float
    solver_threads: int
    verbose_solver: bool
    # Budget for the no-storage bootstrap that seeds each solve. Zero selects
    # max(60 s, 30% of solver_time_limit_seconds). The bootstrap is cached per
    # scenario set, so this is paid once per distinct scenario set, not per solve.
    warm_start_time_limit_seconds: float = 0.0
    # Backup generator rating at the generator bus. It scales with the facility
    # it backs up, so it belongs in configuration rather than in the model body.
    backup_generator_mw: float = 1.0
    backup_generator_mvar: float = 0.8
    # Absolute optimality tolerance in dollars, applied alongside the relative
    # one; the solver stops when either is met, so this only helps if it is the
    # tighter of the two. Zero leaves only the relative tolerance.
    #
    # It exists because the relative tolerance is measured against an objective
    # that is mostly energy purchase, invariant to the design. Storage is worth
    # roughly 30,000 on a 1.55M objective, i.e. 1.86%, so a 2% relative gap makes
    # "install nothing" an acceptable incumbent: measured, three of five
    # no-storage plans were returned as 'optimal' in 34-41 s while every plan
    # that did install something took a median of 911 s. At that setting the
    # tolerance, not the economics, chose the design.
    solver_absolute_gap_dollars: float = 0.0
    # Lower bound on installed sites, for enumerating the siting decision. With
    # only max_storage_sites in force, restricting the candidate list to one bus
    # gives "build there or build nothing", so every part of the enumeration
    # still contains the no-storage case, still branches on build/no-build, and
    # is still seeded by the no-storage bootstrap -- which is the seed the joint
    # model was measured never to leave. Setting this to 1 makes each part answer
    # the question it is meant to answer, given that a battery is built here how
    # large and how scheduled, and leaves build-versus-no-build to the explicit
    # max_storage_sites=0 part. The union of the parts is still exactly the
    # original feasible region, so the decomposition stays an equivalence.
    min_storage_sites: int = 0
    # Solve a free one-site planning problem as the exact disjoint union of the
    # no-storage part and one forced-build part per candidate bus.  This removes
    # the joint siting search failure without relaxing or otherwise changing the
    # feasible region.  Fixed-design dispatch problems are not enumerated.
    enumerate_storage_sites: bool = False
    # Time budget for each forced-site part.  Zero inherits the ordinary solver
    # time limit.  The dataset-v2 budget sweep established 60 s as the first
    # budget that produced an incumbent for every tested subset and bus.
    enumeration_site_time_limit_seconds: float = 0.0
    # Absolute gap used by the enumerated parts.  Their relative gap is fixed at
    # zero deliberately: comparison is by incumbent under an equal time budget,
    # not by accepting a no-storage incumbent against the large common cost.
    enumeration_absolute_gap_dollars: float = 0.0
    # Minimum displacement power factor the PV and storage inverters hold, which
    # sets how much reactive power each may exchange: |Q| <= tan(acos(pf)) times
    # the active rating. IEEE 1547-2018 requires grid-support reactive capability
    # of every interconnected inverter. Without it the only reactive sources on
    # this feeder are the substation and the backup generator, and the generator
    # splits its output equally across phases, so an outage leaves the heavily
    # loaded phases unable to hold the 0.95 pu voltage floor however large the
    # battery is. 1.0 disables the capability and reproduces the original
    # unity-power-factor model.
    inverter_power_factor: float = 1.0
    # Whether the backup generator dispatches per phase. It is a three-phase
    # machine on an unbalanced feeder; splitting its output equally wastes the
    # lightly loaded phase's share and was measured to make every multi-hour
    # outage infeasible. False keeps the original equal split.
    per_phase_backup_generator: bool = False
    # SCIP search strategy. These change how the solver searches, never what it
    # is solving, so the formulation is untouched. Decision-focused training
    # ranks samples by their incumbent objective, so reaching a good primal
    # solution quickly matters more than proving optimality; 'feasibility' plus
    # aggressive heuristics targets exactly that. Leave at the defaults when
    # producing final numbers that are reported as optima.
    solver_emphasis: str = "default"
    solver_aggressive_heuristics: bool = False
    # Planning solves that may run concurrently in isolated workers. Samples
    # within one DFL epoch are independent, so this is the main lever on
    # wall-clock time. Zero selects one worker, i.e. the original serial path.
    # Each worker holds a full copy of the model, so memory scales with this just
    # as much as speed does; a layered-carbon model at K=3 is large enough that
    # four concurrent workers can exhaust a 16 GB machine.
    solver_max_parallel_workers: int = 1
    # Which solver builds and solves the planning problem. Under the production
    # formulation the model is a pure MILP, which is where the gap between
    # solvers is widest, so this is worth having as a switch. 'gurobi' needs
    # gurobipy plus a license large enough for the model; the bundled restricted
    # license stops at 2000 variables and this model has tens of thousands.
    solver_backend: str = "scip"
    # Per-solve memory budget in MB; zero leaves SCIP unbounded. Without a budget
    # SCIP aborts the entire process on allocation failure and the run dies. With
    # one it stops at 'memorylimit' and returns its incumbent, which the pipeline
    # can still use. Budget roughly (usable RAM) / solver_max_parallel_workers.
    solver_memory_limit_mb: float = 0.0
    # How the McCormick relaxation bounds incoming power, which is what decides
    # whether a carbon cap can bind at all.
    #
    # The envelope's useful direction is incoming_carbon <= bound * nodal_carbon,
    # i.e. nodal_carbon >= incoming_carbon / bound, so a loose bound weakens the
    # cap in proportion. "line_rating" sums line thermal ratings, which on this
    # feeder exceed real flows by more than an order of magnitude: with it, a cap
    # of 0.05 tCO2/MWh stays feasible even though the cleanest grid hour is 0.171
    # and no bus can physically be cleaner than its supply. The carbon cap is
    # then decorative -- measured, it never binds at any value.
    #
    # "demand" bounds incoming power by what the bus can actually absorb, using
    # the model's own balance identity
    #     incoming = load + charge + reverse_in + forward_out
    # every term of which is nonnegative, so bounding each term by its own
    # maximum bounds the sum. It is combined with the rating bound by min, so
    # enabling it can only tighten the relaxation, never admit a new solution.
    #
    # Default is "line_rating" so existing runs reproduce. Validate a switch by
    # solving once with a NON-binding cap under both settings: the objectives
    # must match, which shows the tighter bound cut off nothing feasible.
    carbon_envelope_bound: str = "line_rating"
    # Temporal compliance boundary for system-average and layered-system carbon
    # accounting. "hourly" applies the target to every interval; "horizon"
    # applies one energy-weighted budget after summing exact interval emissions.
    carbon_cap_scope: str = "hourly"
    # "shared_feeder" co-optimizes location and lets discharge serve any load.
    # "dedicated_dc" fixes installation at the data-center bus, sizes P/E, and
    # reserves every unit of storage discharge for data-center consumption.
    # "fixed_dc_siting" fixes installation at the data-center bus and sizes
    # P/E, but keeps the physical feeder-wide COPF power balance.  It is the
    # appropriate mode for the exact nodal-carbon/vintage benchmark.
    storage_service_mode: str = "shared_feeder"
    # Physical topology solved by the planning oracle. ``ieee13`` retains the
    # original unbalanced feeder model; ``single_pcc`` aggregates the facility,
    # PV, diesel generator and battery behind one point of common coupling.
    topology: str = "ieee13"
    # Direct combustion intensity of the backup diesel generator. Keeping this
    # in configuration makes the PCC carbon ledger auditable and avoids the
    # historical hard-coded 0.72 tCO2/MWh constant.
    diesel_carbon_t_per_mwh: float = 0.72
    # Optional carbon-intensity allowance for intervals when the grid is down.
    # Zero keeps dc_carbon_cap in every interval. A positive value gives outage
    # energy its own budget while normal grid-connected energy retains the
    # ordinary cap. This separates emergency reliability from routine carbon
    # compliance without removing outage emissions from the ledger.
    outage_carbon_cap: float = 0.0
    # PCC shedding represents involuntary outage curtailment, not an economic
    # substitute for paying the grid-connected carbon-excess penalty.
    allow_grid_connected_shedding: bool = False


@dataclass(frozen=True)
class CostConfig:
    capital_recovery_factor: float
    site_dollars: float
    power_dollars_per_mw: float
    energy_dollars_per_mwh: float
    degradation_dollars_per_mwh: float
    demand_dollars_per_mw_year: float
    curtailment_dollars_per_mwh: float
    shedding_dollars_per_mwh: float
    generator_dollars_per_mwh: float = 125.0
    # Diagnostic slack for an urgent hourly cap, priced in physical $/tCO2.
    # It exists only when allow_carbon_slack=True; otherwise the cap is hard.
    carbon_excess_dollars_per_t: float = 300000.0
    # Multiplies site, power and energy CAPEX together for a declared
    # sensitivity case. Operating, degradation and carbon prices are unchanged.
    battery_capex_scale: float = 1.0


@dataclass(frozen=True)
class ExperimentConfig:
    seed: int
    data: DataConfig
    cvae: CVAEConfig
    dfl: DFLConfig
    planning: PlanningConfig
    costs: CostConfig
    output_dir: Path
    # Optional so configurations written before generators became pluggable keep
    # loading and keep selecting the CVAE.
    generator: GeneratorConfig = field(default_factory=GeneratorConfig)
    # Optional so configurations written before the data-center scale became
    # tunable keep loading and keep the original edge-scale facility.
    data_center: DataCenterConfig = field(default_factory=DataCenterConfig)


def _construct(section_type: type, raw: dict[str, Any]) -> Any:
    return section_type(**raw)


def _generator_config(raw: dict[str, Any] | None) -> GeneratorConfig:
    payload = dict(raw or {})
    return GeneratorConfig(kind=str(payload.get("kind", "cvae")))


def load_config(path: str | Path) -> ExperimentConfig:
    config_path = Path(path).expanduser().resolve()
    with config_path.open("r", encoding="utf-8") as stream:
        raw = yaml.safe_load(stream)
    data_raw = dict(raw["data"])
    data_raw["dataset_path"] = (
        config_path.parent.parent / data_raw["dataset_path"]
    ).resolve()
    return ExperimentConfig(
        seed=int(raw["seed"]),
        data=_construct(DataConfig, data_raw),
        cvae=_construct(CVAEConfig, raw["cvae"]),
        dfl=_construct(DFLConfig, raw["dfl"]),
        planning=_construct(PlanningConfig, raw["planning"]),
        costs=_construct(CostConfig, raw["costs"]),
        output_dir=(config_path.parent.parent / raw["output_dir"]).resolve(),
        generator=_generator_config(raw.get("generator")),
        data_center=_construct(DataCenterConfig, dict(raw.get("data_center", {}))),
    )
