"""Run the DFL stage several times under one support-init rule, one seed each.

A single DFL run says almost nothing here. The K=1 random baseline has sd 3,439
on a mean of 7,614 -- a spread of 7.8x between its worst and best draw -- so one
number cannot be ranked against that distribution. This produces the matching
distribution for DFL.

Each seed gets its own output directory because every artifact the stage writes
is keyed by method alone (dfl_support_<method>.pt, result_<method>.json), so
runs sharing a directory would overwrite each other. The generator checkpoint and
normalization are copied in rather than retrained: the comparison is about the
support search, and retraining the generator per seed would change two things at
once.

    python scripts/run_dfl_seeds.py --rule kmeans --seeds 0 1 2 3 4
    python scripts/run_dfl_seeds.py --rule farthest --seeds 0 --tag baseline
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
# Copied into each run directory. The stage reads the generator and the codec
# normalization from its own output_dir, so they have to be present there.
GENERATOR_ARTIFACTS = ("cvae.pt", "normalization.json")


def build_config(base: Path, out_yaml: Path, seed: int, rule: str, run_dir: Path,
                 epochs: int | None = None) -> None:
    raw = yaml.safe_load(base.read_text(encoding="utf-8"))
    raw["seed"] = seed
    raw["dfl"]["support_init_rule"] = rule
    if epochs is not None:
        raw["dfl"]["epochs"] = epochs
    # load_config resolves output_dir against the config's parent's parent, so a
    # generated config living in configs/ keeps the same repo-relative meaning.
    raw["output_dir"] = f"outputs/{run_dir.name}"
    header = (
        f"# Generated by scripts/run_dfl_seeds.py from {base.name}.\n"
        f"# seed={seed}  dfl.support_init_rule={rule}\n"
        "# Comments from the base config are not preserved here; edit the base.\n"
    )
    out_yaml.write_text(header + yaml.safe_dump(raw, sort_keys=False), encoding="utf-8")


def run(command: list[str], log: Path) -> int:
    with log.open("w", encoding="utf-8") as handle:
        completed = subprocess.run(command, cwd=REPO, stdout=handle,
                                   stderr=subprocess.STDOUT, text=True)
    return completed.returncode


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base-config", default="configs/generator_compare_k1t2.yaml")
    # farthest, which is also the config default. It was briefly worth avoiding:
    # at solver_relative_gap 1e-3 it scored 862 against kmeans at 3,313 and
    # looked like the worst possible seed. That was solver noise -- the same
    # rule returned 862 and 3,050 on two runs of the same measurement -- and at
    # 1e-4 it is the best deterministic rule there is, 4,294 against kmeans at
    # 4,141.
    #
    # Note farthest ignores the seed, so a multi-seed sweep over it varies only
    # the policy sampling and every run starts from the same scenario. That
    # isolates the search's own variance, which is the headline question. Use
    # --rule kmeans for a second set if the start needs to vary too: it is the
    # answer to "is this sensitive to where it began".
    ap.add_argument("--rule", default="farthest",
                    help="dfl.support_init_rule for every run")
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2, 3, 4])
    ap.add_argument("--tag", default=None, help="directory tag; defaults to the rule")
    ap.add_argument("--source-run", default="outputs/generator_comparison_k1t2_48h",
                    help="directory holding the trained generator to copy in")
    # Evaluation runs one solve over final_validation_size scenarios while
    # solver_memory_limit_mb is sized for several concurrent training solves.
    # Measured peak for that solve is 2,885 MB; give it room since it runs alone.
    ap.add_argument("--eval-memory-limit", type=float, default=8000.0)
    ap.add_argument("--epochs", type=int, default=None,
                    help="override dfl.epochs; use a small value to smoke-test "
                         "the pipeline before committing to a full run")
    # Off by default because five runs write five event directories and the
    # per-seed train.log already carries the same numbers. On when the shape of
    # the training curve is the question, which the log makes tedious to read.
    ap.add_argument("--tensorboard", action="store_true",
                    help="write tensorboard events (one directory per seed, "
                         "under each run's output_dir)")
    args = ap.parse_args()

    python = sys.executable
    base = REPO / args.base_config
    source = REPO / args.source_run
    tag = args.tag or args.rule
    for artifact in GENERATOR_ARTIFACTS:
        if not (source / artifact).exists():
            raise SystemExit(f"missing generator artifact: {source / artifact}")

    rows = []
    for seed in args.seeds:
        name = f"dfl_k1_{tag}_seed{seed}"
        run_dir = REPO / "outputs" / name
        run_dir.mkdir(parents=True, exist_ok=True)
        for artifact in GENERATOR_ARTIFACTS:
            target = run_dir / artifact
            if not target.exists():
                shutil.copy2(source / artifact, target)

        cfg = REPO / "configs" / f"_generated_{name}.yaml"
        build_config(base, cfg, seed, args.rule, run_dir, epochs=args.epochs)
        rel_cfg = str(cfg.relative_to(REPO)).replace("\\", "/")

        print(f"\n=== {name} (rule={args.rule}, seed={seed}) ===", flush=True)
        started = time.perf_counter()
        train_cmd = [python, "scripts/train_dfl.py", "--config", rel_cfg]
        if not args.tensorboard:
            train_cmd.append("--no-tensorboard")
        code = run(train_cmd, run_dir / "train.log")
        train_seconds = time.perf_counter() - started
        if code != 0:
            print(f"  TRAIN FAILED (exit {code}); see {run_dir / 'train.log'}", flush=True)
            rows.append({"seed": seed, "status": "train_failed"})
            continue
        print(f"  trained in {train_seconds / 60:.1f} min", flush=True)

        started = time.perf_counter()
        code = run([python, "scripts/evaluate.py", "--config", rel_cfg,
                    "--memory-limit", str(args.eval_memory_limit)],
                   run_dir / "evaluate.log")
        eval_seconds = time.perf_counter() - started
        if code != 0:
            print(f"  EVAL FAILED (exit {code}); see {run_dir / 'evaluate.log'}", flush=True)
            rows.append({"seed": seed, "status": "eval_failed"})
            continue

        result = json.loads((run_dir / "result_reinforce.json").read_text())
        design = result["planning"]["design"]
        installed = [b for b, v in design["site"].items() if v > 0]
        row = {
            "seed": seed,
            "rule": args.rule,
            "status": "ok",
            "storage_value": result["storage_value"],
            "out_of_sample_objective": result["out_of_sample_validation"]["objective"],
            "out_of_sample_status": result["out_of_sample_validation"]["status"],
            "objectives_comparable": result["objectives_comparable"],
            "installed": installed,
            "energy_mwh": sum(design["energy_mwh"][b] for b in installed),
            "generated_price_spread": result["scenario_summary"]["generated"][
                "weighted_price_spread_per_mwh"],
            "support_source_names": json.loads(
                (run_dir / "dfl_result_reinforce.json").read_text()
            )["support_source_names"],
            "train_minutes": round(train_seconds / 60, 1),
            "eval_minutes": round(eval_seconds / 60, 1),
        }
        rows.append(row)
        print(f"  storage_value {row['storage_value']:,.0f}   "
              f"E={row['energy_mwh']:.3f} MWh   "
              f"spread={row['generated_price_spread']:.2f}   "
              f"eval {eval_seconds / 60:.1f} min", flush=True)

        summary = REPO / "outputs" / f"dfl_seeds_{tag}.json"
        summary.write_text(json.dumps(rows, indent=2))

    ok = [r for r in rows if r.get("status") == "ok"]
    print(f"\n=== {len(ok)}/{len(rows)} runs completed ===")
    if ok:
        values = [r["storage_value"] for r in ok]
        mean = sum(values) / len(values)
        print(f"storage_value: mean {mean:,.0f}  min {min(values):,.0f}  max {max(values):,.0f}")
        if len(values) > 1:
            sd = (sum((v - mean) ** 2 for v in values) / (len(values) - 1)) ** 0.5
            print(f"               sd {sd:,.0f}")
        print(f"\nwritten outputs/dfl_seeds_{tag}.json")


if __name__ == "__main__":
    main()
